describe("config", function()
  local config = require("pi-traycer.config")

  before_each(function()
    package.loaded["pi-traycer.config"] = nil
    config = require("pi-traycer.config")
  end)

  it("has default values", function()
    config.setup({})
    local opts = config.get()
    assert.are.equal("right", opts.chat.position)
    assert.are.equal(0.4, opts.chat.size)
    assert.are.equal("bottom", opts.plan.position)
    assert.are.equal(0.3, opts.plan.size)
    assert.are.equal("<leader>pc", opts.keymaps.chat)
    assert.is_true(opts.notifications.cost_on_completion)
    assert.are.equal(80, opts.notifications.context_warning_pct)
  end)

  it("merges user opts over defaults", function()
    config.setup({ chat = { size = 0.5 }, pi = { model = "test-model" } })
    local opts = config.get()
    assert.are.equal(0.5, opts.chat.size)
    assert.are.equal("right", opts.chat.position)
    assert.are.equal("test-model", opts.pi.model)
  end)

  it("allows disabling keymaps with false", function()
    config.setup({ keymaps = { chat = false } })
    local opts = config.get()
    assert.is_false(opts.keymaps.chat)
    assert.are.equal("<leader>pe", opts.keymaps.epic)
  end)
end)
